# Generated by Django 6.0.3 on 2026-03-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_remove_cliente_email_remove_cliente_telefone_and_more'),
        ('quartos', '0003_remove_quarto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_conducao', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('ape', 'A pé'), ('2_carros', '2 Carros'), ('taxi', 'Taxi'), ('uber', 'Uber'), ('uber_moto', 'Uber Moto')], max_length=20)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quartos.quarto', verbose_name='Quarto')),
                ('veiculo_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal', to='clientes.veiculo', verbose_name='Veículo Principal')),
                ('veiculo_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secundario', to='clientes.veiculo', verbose_name='Veículo Secundário')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('estrangeiro', models.BooleanField(default=False, verbose_name='Estrangeiro')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='reservas.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
