# Generated by Django 6.0.2 on 2026-02-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número do Quarto')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo do Quarto')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Hora')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('manutencao', 'Em Manutenção')], default='disponivel', max_length=20, verbose_name='Status do Quarto')),
                ('esta_ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='empresas.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
