# Generated by Django 6.0.2 on 2026-03-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('standard', 'Standard'), ('luxo', 'Luxo'), ('super_luxo', 'Super Luxo'), ('presidencial', 'Presidencial'), ('tematica', 'Temática')], max_length=50, verbose_name='Tipo do Quarto'),
        ),
    ]
