# Generated by Django 6.0.3 on 2026-03-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quartos', '0002_alter_quarto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='empresa',
        ),
    ]
