# Generated by Django 6.0.2 on 2026-03-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(choices=[('gerente', 'Gerente'), ('recepcionista', 'Recepcionista'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção')], max_length=20, verbose_name='Cargo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='empresas.empresa', verbose_name='Empresa')),
            ],
        ),
    ]
