# Generated by Django 6.0.3 on 2026-03-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
    ]
