# Generated by Django 6.0.3 on 2026-03-17 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('prata', 'Prata'), ('vermelho', 'Vermelho'), ('azul', 'Azul'), ('outro', 'Outro')], max_length=20)),
                ('cor_personalizada', models.CharField(blank=True, max_length=30, null=True)),
                ('modelo', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='veiculos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
