# Generated by Django 6.0.3 on 2026-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_email_remove_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='estrangeiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modo_conducao',
            field=models.CharField(choices=[('proprio', 'Veículo Próprio'), ('uber', 'Uber'), ('moto-uber', 'Moto-Uber'), ('taxi', 'Táxi'), ('a_pe', 'A pé')], default='proprio', max_length=20, verbose_name='Modo de Condução'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(choices=[('preto', 'Preto'), ('branco', 'Branco'), ('prata', 'Prata'), ('vermelho', 'Vermelho'), ('azul', 'Azul'), ('outro', 'Outro')], max_length=20, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, verbose_name='Placa'),
        ),
    ]
