# Generated by Django 6.0.3 on 2026-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_veiculo_estrangeiro_veiculo_modo_conducao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='estrangeiro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estrangeiro',
            field=models.BooleanField(default=False),
        ),
    ]
