# Generated by Django 6.0.3 on 2026-03-18 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_veiculo_estrangeiro_cliente_estrangeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='clientes.veiculo', verbose_name='Veículo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, verbose_name='Placa'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('veiculo', 'cpf')},
        ),
    ]
